name: Build and Deploy to S3

on:

  push:

    branches: [ master ]

  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: us-east-1

      # 1) Sync everything except CI files (this will create assets/ paths in S3)

      - name: Sync site (assets, css, etc.)

        run: |

          aws s3 sync . s3://myresumehostingforshivraj --delete \

            --exclude ".git/*" \

            --exclude ".github/*" \

            --exclude ".gitignore"

      # 2) Push a no-cache index.html so browsers/CDN always fetch latest

      - name: Upload index.html (no cache)

        run: |

          aws s3 cp index.html s3://myresumehostingforshivraj/index.html \

            --cache-control "no-store, max-age=0, must-revalidate" \

            --content-type "text/html"
 